spring.application.name=proyectofinal
spring.datasource.url=jdbc:postgresql://localhost:5432/AJCare
spring.datasource.username=postgres
spring.datasource.password=antonia14_
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
